name: 🐞 Bug Report
description: Report a bug or issue in the library
title: "[Bug Report]: "

body:
  - type: textarea
    id: bugDescription
    attributes:
      label: 📝 Bug Description
      description: Describe the bug or issue you encountered in detail.
      placeholder: Provide a clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: reproductionSteps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: Describe the actions you took leading to the issue.
    validations:
      required: true
  - type: textarea
    id: expectedBehavior
    attributes:
      label: 🤔 Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Explain the correct behavior you anticipated.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in our library. Please provide the following information to help us investigate and resolve the issue.
        
        **By submitting this issue, you are agreeing to follow our [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md).**
        **Before you proceed, please review our [Contributing Guidelines](../blob/main/.github/CONTRIBUTING_GUIDELINE.md).**
        
        Your feedback is valuable to us!
