name: 📖 Documentation Update
description: Suggest improvements or corrections to the documentation
title: "[Documentation Update]: "

body:
  - type: textarea
    id: docLocation
    attributes:
      label: 📚 Documentation Location
      description: Specify the location or page in the documentation that needs updates.
      placeholder: Provide the URL or path to the documentation.
    validations:
      required: true
  - type: textarea
    id: proposedChanges
    attributes:
      label: 🔄 Proposed Changes
      description: Describe the improvements or corrections you'd like to suggest.
      placeholder: Explain what changes should be made and why.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting improvements to our documentation. Please provide the following information to help us make our documentation better.
        
        **By submitting this issue, you are agreeing to follow our [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md).**
        **Before you proceed, please review our [Contributing Guidelines](../blob/main/.github/CONTRIBUTING_GUIDELINE.md).**
        
        Your contribution is appreciated!
